### ISSUE TITLE
Use your own application coordinates

### ISSUE THREAD

**Issue by pkg01** [Azure-Samples/active-directory-dotnet-desktop-msgraph-v2#52]
Followed the steps given in [Optional] Use your own application coordinates section.

## Got this error when used personal account to login

Error Acquiring Token:
MSAL.Desktop.4.13.0.0.MsalUiRequiredException: 
	ErrorCode: invalid_grant
Microsoft.Identity.Client.MsalUiRequiredException: AADSTS70000: The provided value for the 'code' parameter is not valid.
Trace ID: 1166ef2a-e2d5-466d-aa83-185779210b00
Correlation ID: 6fb3cb29-c7f9-4dfb-a160-709ab2dc3447
Timestamp: 2020-05-22 19:06:42Z
   at Microsoft.Identity.Client.OAuth2.OAuth2Client.ThrowServerException(HttpResponse response, RequestContext requestContext)
   at Microsoft.Identity.Client.OAuth2.OAuth2Client.CreateResponse[T](HttpResponse response, RequestContext requestContext, Boolean addCorrelationId)
   at Microsoft.Identity.Client.OAuth2.OAuth2Client.<ExecuteRequestAsync>d__11`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

## Got this error when used a new user under the new active directory.

Error Acquiring Token:
MSAL.Desktop.4.13.0.0.MsalServiceException: 
	ErrorCode: invalid_client
Microsoft.Identity.Client.MsalServiceException: A configuration issue is preventing authentication - check the error message from the server for details.You can modify the configuration in the application registration portal. See https://aka.ms/msal-net-invalid-client for details.  Original exception: AADSTS7000218: The request body must contain the following parameter: 'client_assertion' or 'client_secret'.
Trace ID: 281bacfa-59c3-47d0-9e47-faf8d7b10b00
Correlation ID: 97af5c20-b421-414d-bf96-d3e6470038de
Timestamp: 2020-05-22 19:15:26Z
   at Microsoft.Identity.Client.OAuth2.OAuth2Client.ThrowServerException(HttpResponse response, RequestContext requestContext)
   at Microsoft.Identity.Client.OAuth2.OAuth2Client.CreateResponse[T](HttpResponse response, RequestContext requestContext, Boolean addCorrelationId)
   at Microsoft.Identity.Client.OAuth2.OAuth2Client.<ExecuteRequestAsync>d__11`1.MoveNext()
--- End of stack trace from previous location where exception was thrown --

**Comment by jmprieur** [comment]
@pkg01
Did you follow the instructions, in particular for the redirect URI? 
Did you use the application creation scripts?
https://github.com/Azure-Samples/active-directory-dotnet-desktop-msgraph-v2/blob/msal3x/AppCreationScripts/AppCreationScripts.md

**Comment by adreno-abhi** [comment]
Hi,

I downloaded the sample and got it working wothout issues. Also adding my own coordinates by registering the app on azure and using the client and tenant id also works absolutely fine. 

The issue comes when we try to use the same app on some other system. As soon as we try using it on other system, it starts throwing the following exception on the line:

**var accounts = await app.GetAccountsAsync();**

Do let me know why this is happening and how can i resolve this.

**Exception Details**


System.Security.Cryptography.CryptographicException
  HResult=0x8009000B
  Message=Key not valid for use in specified state.

  Source=System.Security
  StackTrace:
   at System.Security.Cryptography.ProtectedData.Unprotect(Byte[] encryptedData, Byte[] optionalEntropy, DataProtectionScope scope)
   at active_directory_wpf_msgraph_v2.TokenCacheHelper.BeforeAccessNotification(TokenCacheNotificationArgs args) in E:\366Pi\BitBucket\DesktopApplication\active-directory-wpf-msgraph-v2\TokenCacheHelper.cs:line 65
   at Microsoft.Identity.Client.TokenCache.OnBeforeAccess(TokenCacheNotificationArgs args) in C:\agent2\_work\69\s\src\Microsoft.Identity.Client\TokenCache.cs:line 147
   at Microsoft.Identity.Client.TokenCache.GetAccounts(String authority, Boolean validateAuthority, RequestContext requestContext) in C:\agent2\_work\69\s\src\Microsoft.Identity.Client\TokenCache.cs:line 805
   at Microsoft.Identity.Client.ClientApplicationBase.GetAccountsAsync() in C:\agent2\_work\69\s\src\Microsoft.Identity.Client\ClientApplicationBase.cs:line 202
   at active_directory_wpf_msgraph_v2.MainWindow.<CallGraphButton_Click>d__3.MoveNext() in E:\366Pi\BitBucket\DesktopApplication\active-directory-wpf-msgraph-v2\MainWindow.xaml.cs:line 49
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run(Window window)
   at System.Windows.Application.Run()
   at active_directory_wpf_msgraph_v2.App.Main()

  This exception was originally thrown at this call stack:
    System.Security.Cryptography.ProtectedData.Unprotect(byte[], byte[], System.Security.Cryptography.DataProtectionScope)
    active_directory_wpf_msgraph_v2.TokenCacheHelper.BeforeAccessNotification(Microsoft.Identity.Client.TokenCacheNotificationArgs) in TokenCacheHelper.cs
    Microsoft.Identity.Client.TokenCache.OnBeforeAccess(Microsoft.Identity.Client.TokenCacheNotificationArgs) in TokenCache.cs
    Microsoft.Identity.Client.TokenCache.GetAccounts(string, bool, Microsoft.Identity.Client.Core.RequestContext) in TokenCache.cs
    Microsoft.Identity.Client.ClientApplicationBase.GetAccountsAsync() in ClientApplicationBase.cs
    active_directory_wpf_msgraph_v2.MainWindow.CallGraphButton_Click(object, System.Windows.RoutedEventArgs) in MainWindow.xaml.cs
    System.Runtime.CompilerServices.AsyncMethodBuilderCore.ThrowAsync.AnonymousMethod__6_0(object)
    System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, object, int)
    System.Windows.Threading.ExceptionWrapper.TryCatchWhen(object, System.Delegate, object, int, System.Delegate)
    System.Windows.Threading.DispatcherOperation.InvokeImpl()
    ...
    [Call Stack Truncated]
