### ISSUE TITLE
System.Security.Cryptography.CryptographicException: 'Key not valid for use in specified state.

### ISSUE THREAD

**Issue by adreno-abhi** [Azure-Samples/active-directory-dotnet-desktop-msgraph-v2#56]
Hi,

I downloaded the sample and got it working wothout issues. Also adding my own coordinates by registering the app on azure and using the client and tenant id also works absolutely fine.

The issue comes when we try to use the same app on some other system. As soon as we try using it on other system, it starts throwing the following exception on the line:

**var accounts = await app.GetAccountsAsync();**

Do let me know why this is happening and how can i resolve this.

**Exception Details**

System.Security.Cryptography.CryptographicException
HResult=0x8009000B
Message=Key not valid for use in specified state.

Source=System.Security
StackTrace:
at System.Security.Cryptography.ProtectedData.Unprotect(Byte[] encryptedData, Byte[] optionalEntropy, DataProtectionScope scope)
at active_directory_wpf_msgraph_v2.TokenCacheHelper.BeforeAccessNotification(TokenCacheNotificationArgs args) in E:\366Pi\BitBucket\DesktopApplication\active-directory-wpf-msgraph-v2\TokenCacheHelper.cs:line 65
at Microsoft.Identity.Client.TokenCache.OnBeforeAccess(TokenCacheNotificationArgs args) in C:\agent2_work\69\s\src\Microsoft.Identity.Client\TokenCache.cs:line 147
at Microsoft.Identity.Client.TokenCache.GetAccounts(String authority, Boolean validateAuthority, RequestContext requestContext) in C:\agent2_work\69\s\src\Microsoft.Identity.Client\TokenCache.cs:line 805
at Microsoft.Identity.Client.ClientApplicationBase.GetAccountsAsync() in C:\agent2_work\69\s\src\Microsoft.Identity.Client\ClientApplicationBase.cs:line 202
at active_directory_wpf_msgraph_v2.MainWindow.<CallGraphButton_Click>d__3.MoveNext() in E:\366Pi\BitBucket\DesktopApplication\active-directory-wpf-msgraph-v2\MainWindow.xaml.cs:line 49
at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.b__6_0(Object state)
at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
at System.Windows.Threading.DispatcherOperation.InvokeImpl()
at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
at System.Windows.Threading.DispatcherOperation.Invoke()
at System.Windows.Threading.Dispatcher.ProcessQueue()
at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
at System.Windows.Application.RunDispatcher(Object ignore)
at System.Windows.Application.RunInternal(Window window)
at System.Windows.Application.Run(Window window)
at System.Windows.Application.Run()
at active_directory_wpf_msgraph_v2.App.Main()

This exception was originally thrown at this call stack:
System.Security.Cryptography.ProtectedData.Unprotect(byte[], byte[], System.Security.Cryptography.DataProtectionScope)
active_directory_wpf_msgraph_v2.TokenCacheHelper.BeforeAccessNotification(Microsoft.Identity.Client.TokenCacheNotificationArgs) in TokenCacheHelper.cs
Microsoft.Identity.Client.TokenCache.OnBeforeAccess(Microsoft.Identity.Client.TokenCacheNotificationArgs) in TokenCache.cs
Microsoft.Identity.Client.TokenCache.GetAccounts(string, bool, Microsoft.Identity.Client.Core.RequestContext) in TokenCache.cs
Microsoft.Identity.Client.ClientApplicationBase.GetAccountsAsync() in ClientApplicationBase.cs
active_directory_wpf_msgraph_v2.MainWindow.CallGraphButton_Click(object, System.Windows.RoutedEventArgs) in MainWindow.xaml.cs
System.Runtime.CompilerServices.AsyncMethodBuilderCore.ThrowAsync.AnonymousMethod__6_0(object)
System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, object, int)
System.Windows.Threading.ExceptionWrapper.TryCatchWhen(object, System.Delegate, object, int, System.Delegate)
System.Windows.Threading.DispatcherOperation.InvokeImpl()
...
[Call Stack Truncated]

**Comment by jmprieur** [comment]
@adreno-abhi 
you might want to remove the tokencache file (which ends in .msalcache.bin3) from the bin\debug or bin\release folder before moving your app to the new system. The token cache in this sample uses DPAPI
